apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ro.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "ro.labels" . | nindent 4 }}
{{- with .Values.podAnnotations }}
annotations:
{{- toYaml . | nindent 8 }}
{{- end }}
data:
  # database
  OSMRO_DATABASE_HOST: "{{ .Values.global.database.host }}"
  OSMRO_DATABASE_PORT: "{{ .Values.global.database.port }}"
  OSMRO_DATABASE_DRIVER: "{{ .Values.global.database.driver }}"
  OSMRO_DATABASE_URI: "{{ .Values.global.database.uri }}"
  {{- if .Values.global.database.user }}
  OSMRO_DATABASE_USER: "{{ .Values.global.database.user }}"
  {{- end }}
  {{- if .Values.global.database.password }}
  OSMRO_DATABASE_PASSWORD: "{{ .Values.global.database.password }}"
  {{- end }}
  # message
  OSMRO_MESSAGE_HOST: "{{ .Values.global.message.host }}"
  OSMRO_MESSAGE_PORT: "{{ .Values.global.message.port }}"
  OSMRO_MESSAGE_DRIVER: "{{ .Values.global.message.driver }}"
  # log
  OSMRO_LOG_LEVEL: "{{ .Values.logLevel }}"
  # ro
  RO_DB_PORT: "{{ .Values.databasePort }}"
  RO_DB_OVIM_PORT: "{{ .Values.databaseOvimPort }}"
  RO_DB_NAME: "{{ .Values.databaseName }}"
  RO_DB_OVIM_NAME: "{{ .Values.databaseOvimName }}"
  OPENMANO_TENANT: "{{ .Values.openmanoTenant }}"
