apiVersion: v1
kind: Service
metadata:
  name: {{ include "ro.fullname" . }}
  labels:
    {{- include "ro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{.Values.service.nodePort}}
      {{ end }}
  selector:
    {{- include "ro.selectorLabels" . | nindent 4 }}
