apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lcm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lcm.labels" . | nindent 4 }}
{{- with .Values.podAnnotations }}
annotations:
{{- toYaml . | nindent 8 }}
{{- end }}
type: Opaque
data:
  # database
  OSMLCM_DATABASE_COMMONKEY: {{ .Values.global.database.commonKey | b64enc | quote }}
  # vca
  OSMLCM_VCA_USER: {{ .Values.global.vca.user | b64enc | quote }}
  OSMLCM_VCA_SECRET: {{ .Values.global.vca.secret | b64enc | quote }}
  {{- if .Values.global.vca.pubKey }}
  OSMLCM_VCA_PUBKEY: {{ .Values.global.vca.pubKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.vca.cacert }}
  OSMLCM_VCA_CACERT: {{ .Values.global.vca.cacert | b64enc | quote }}
  {{- end }}
