apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mon.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mon.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: message-database-connection-test
        image: alpine:latest
        command: ["sh", "-c", "until (nc -zvw1 {{ .Values.global.message.host }} {{ .Values.global.message.port }} && nc -zvw1 {{ .Values.global.database.host }} {{ .Values.global.database.port }}); do sleep 3; done; exit 0"]
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "mon.fullname" . }}
          - secretRef:
              name: {{ include "mon.fullname" . }}
          ports:
            - name: http
              containerPort: 8662
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
