apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pol.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "pol.labels" . | nindent 4 }}
{{- with .Values.podAnnotations }}
annotations:
{{- toYaml . | nindent 8 }}
{{- end }}
data:
  # database
  OSMPOL_DATABASE_HOST: "{{ .Values.global.database.host }}"
  OSMPOL_DATABASE_PORT: "{{ .Values.global.database.port }}"
  OSMPOL_DATABASE_DRIVER: "{{ .Values.global.database.driver }}"
  OSMPOL_DATABASE_URI: "{{ .Values.global.database.uri }}"
  # message
  OSMPOL_MESSAGE_HOST: "{{ .Values.global.message.host }}"
  OSMPOL_MESSAGE_PORT: "{{ .Values.global.message.port }}"
  OSMPOL_MESSAGE_DRIVER: "{{ .Values.global.message.driver }}"
  # sql
  OSMPOL_SQL_DATABASE_URI: "{{ .Values.global.sqlUri }}"
  # log
  OSMPOL_GLOBAL_LOG_LEVEL: "{{ .Values.logLevel }}"
  OSMPOL_SQL_DATABASE_URI: "{{ .Values.global.sqlDatabaseUri }}"
