apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pol.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pol.labels" . | nindent 4 }}
{{- with .Values.podAnnotations }}
annotations:
{{- toYaml . | nindent 8 }}
{{- end }}
type: Opaque
data:
  OSMPOL_DATABASE_COMMONKEY: {{ .Values.global.database.commonKey | b64enc | quote }}
