apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  clusterIP: None
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  serviceName: mongo
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
        - name: mongo-db
          mountPath: /data/db
      volumes:
      - name: mongo-db
        hostPath:
         path: /var/lib/osm/osm_mongo_db/_data
