apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keystone.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keystone.labels" . | nindent 4 }}
{{- with .Values.podAnnotations }}
annotations:
{{- toYaml . | nindent 8 }}
{{- end }}
type: Opaque
data:
  ROOT_DB_USER: {{ .Values.database.rootUser | b64enc | quote }}
  ROOT_DB_PASSWORD: {{ .Values.database.rootPassword | b64enc | quote }}
  KEYSTONE_DB_PASSWORD: {{ .Values.database.keystonePassword | b64enc | quote }}
  KEYSTONE_HOST: {{ .Values.keystone.host | b64enc | quote }}
  REGION_ID: {{ .Values.keystone.regionId | b64enc | quote }}
  ADMIN_USERNAME: {{ .Values.admin.username | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.admin.password | b64enc | quote }}
  ADMIN_PROJECT: {{ .Values.admin.project | b64enc | quote }}
  SERVICE_USERNAME: {{ .Values.global.nbiAuth.serviceUsername | b64enc | quote }}
  SERVICE_PASSWORD: {{ .Values.global.nbiAuth.servicePassword | b64enc | quote }}
  SERVICE_PROJECT: {{ .Values.global.nbiAuth.serviceProject | b64enc | quote }}
  {{- if .Values.ldap }}
  LDAP_AUTHENTICATION_DOMAIN_NAME: {{ .Values.ldap.authenticationDomainName | b64enc | quote }}
  LDAP_URL: {{ .Values.ldap.url | b64enc | quote }}
  LDAP_BIND_USER: {{ .Values.ldap.bindUser | b64enc | quote }}
  LDAP_BIND_PASSWORD: {{ .Values.ldap.bindPassword | b64enc | quote }}
  LDAP_CHASE_REFERRALS: {{ .Values.ldap.chaseReferrals | b64enc | quote }}
  LDAP_PAGE_SIZE: {{ .Values.ldap.pageSize | b64enc | quote }}
  LDAP_USER_TREE_DN: {{ .Values.ldap.userTreeDN | b64enc | quote }}
  LDAP_USER_OBJECTCLASS: {{ .Values.ldap.userObjectClass | b64enc | quote }}
  LDAP_USER_ID_ATTRIBUTE: {{ .Values.ldap.userIdAttribute | b64enc | quote }}
  LDAP_USER_NAME_ATTRIBUTE: {{ .Values.ldap.userNameAttribute | b64enc | quote }}
  LDAP_USER_PASS_ATTRIBUTE: {{ .Values.ldap.userPassAttribute | b64enc | quote }}
  LDAP_USER_FILTER: {{ .Values.ldap.userFilter | b64enc | quote }}
  LDAP_USER_ENABLED_ATTRIBUTE: {{ .Values.ldap.userEnabledAttribute | b64enc | quote }}
  LDAP_USER_ENABLED_MASK: {{ .Values.ldap.userEnabledMask | b64enc | quote }}
  LDAP_USER_ENABLED_DEFAULT: {{ .Values.ldap.userEnabledDefault | b64enc | quote }}
  LDAP_USER_ENABLED_INVERT: {{ .Values.ldap.userEnabledInvert | b64enc | quote }}
  LDAP_GROUP_OBJECTCLASS: {{ .Values.ldap.groupObjectClass | b64enc | quote }}
  LDAP_GROUP_TREE_DN: {{ .Values.ldap.groupTreeDN | b64enc | quote }}
  LDAP_USE_STARTTLS: {{ .Values.ldap.useStarttls | b64enc | quote }}
  LDAP_TLS_CACERT_BASE64: {{ .Values.ldap.tlsCacertBase64 | b64enc | quote }}
  LDAP_TLS_REQ_CERT: {{ .Values.ldap.tlsReqCert | b64enc | quote }}
  {{- end }}
